# Generated by Django 4.2.3 on 2023-08-03 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_alter_contact_options_alter_contact_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'",
                        regex="^\\+?1?[-().\\dx]{9,15}$",
                    )
                ],
            ),
        ),
    ]
