# Generated by Django 4.2.3 on 2023-08-04 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0007_alter_contact_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["created_at", "name"]},
        ),
    ]
